name: Dart Test for login-only endpoints

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDEX: ${{ secrets.MD_PASS }}

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      - name: Create dotenv
        run: echo "MDPASS=$MDEX" > .env

      - name: Run tests
        run: dart test ./tetst/logged_in_test.dart
